/**
 * Expo config plugin: raise any CocoaPods target below the app's minimum iOS
 * version up to it.
 *
 * Xcode 26+ refuses to build pod targets whose IPHONEOS_DEPLOYMENT_TARGET is
 * below iOS 15.0. Several resource-bundle pods (SDWebImage, RNCAsyncStorage,
 * RNSVG, react-native-maps, Sentry) still declare 9.0–13.4, which fails the
 * build with "deployment target ... is set to X, but the range of supported
 * deployment target versions is 15.0 to ...".
 *
 * `ios/` is generated by `expo prebuild` and is not committed, so the fix lives
 * here rather than in a hand-edited Podfile.
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '# [kilimo] raise legacy pod deployment targets';
const MIN_IOS = '15.1';

const SNIPPET = `
    ${MARKER}
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        current = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current && current.to_f < ${MIN_IOS}
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${MIN_IOS}'
        end
      end
    end
`;

module.exports = function withPodsDeploymentTarget(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let podfile = fs.readFileSync(podfilePath, 'utf8');
      if (podfile.includes(MARKER)) return cfg; // already patched (idempotent)

      // Append inside the existing post_install block, right after the
      // react_native_post_install(...) call closes.
      const anchor = /react_native_post_install\([\s\S]*?\n\s*\)\n/;
      if (!anchor.test(podfile)) {
        throw new Error(
          '[withPodsDeploymentTarget] Could not find react_native_post_install(...) in Podfile'
        );
      }
      podfile = podfile.replace(anchor, (m) => m + SNIPPET);
      fs.writeFileSync(podfilePath, podfile);
      return cfg;
    },
  ]);
};
